[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_summer_t22 = "CRbduMFSfVvUDuChQrhjhaRD8MgoaAr5Dnyr6F3knKte"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
